version: '3.3'

services:
    rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"

    rabbit-receiver-1:
      build:
        context: rabbit-receiver
        dockerfile: docker/Dockerfile
      restart: always
      ports:
        - "8181:8181"

    rabbit-receiver-2:
      build:
        context: rabbit-receiver
        dockerfile: docker/Dockerfile
      restart: always
      ports:
        - "8182:8181"

    rabbit-sender:
      build:
        context: rabbit-sender
        dockerfile: docker/Dockerfile
      restart: always
      ports:
        - "8180:8180"
