apiVersion: v1
kind: Service
metadata:
  name: rabbit-receiver
  labels:
    app: rabbit-receiver
spec:
  type: LoadBalancer
  ports:
    - port: 8181
  selector:
    app: rabbit-receiver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-receiver
  labels:
    app: rabbit-receiver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit-receiver
    spec:
      containers:
        - name: rabbit-receiver
          image: rabbit-receiver:v1
          ports:
            - containerPort: 8181
  selector:
    matchLabels:
      app: rabbit-receiver
