server:
  port: 8180


spring:
  cloud:
    stream:
      bindings:
        customOutputOne:
          destination: carTopic
          content-type: application/json
        customInput:
          destination: carTopic
          group: timerGroup
          content-type: application/json
      rabbit:
        bindings:
          customInput:
            consumer:
              auto-bind-dlq: true


---
spring:
  profiles: docker 
  rabbitmq:
    host: rabbitmq
    port: 5672