server:
  port: 8180

spring:
  cloud:
    stream:
      bindings:
        customOutputOne:
          destination: carTopic
          content-type: application/json
      rabbit:
        bindings:
          customOutputOne:
            producer:
              exchange-type: fanout



---
spring:
  profiles: docker 
  rabbitmq:
    host: rabbitmq
    port: 5672