server:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        carSender:
          destination: carQueue

---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
