server:
  port: 0

spring:
  cloud:
    stream:
      function:
        definition: carReceiver
      bindings:
        carReceiver-in-0:
          destination: carQueue
          group: my-group
          content-type: application/json
      rabbit:
        bindings:
          carReceiver-in-0:
            consumer:
              auto-bind-dlq: true
---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
