server:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        customInput:
          destination: carTopic
          group: timerGroup
          content-type: application/json

---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
