server:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        carReceiver:
          destination: carQueue
          group: timerGroup
          content-type: application/json
      rabbit:
        bindings:
          carReceiver:
            consumer:
              prefetch: 3
              auto-bind-dlq: true
---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
