server:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        customInput:
          destination: carTopic
          group: timerGroup
          content-type: application/json
      rabbit:
        bindings:
          customInput:
            consumer:
              auto-bind-dlq: true
              exchange-type: fanout

---
spring:
  profiles: fanOutProfile
  cloud:
    stream:
      bindings:
        customInput:
          group: timerQueue

---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
